services:
  flashlink-postgres:
    image: ankane/pgvector
    container_name: flashlink_log_db_postgres
    ports:
      - "5444:5432"
    command: >
      postgres -c timezone=America/Los_Angeles -c max_connections=500 -c shared_buffers=256MB -c work_mem=64MB -c maintenance_work_mem=128MB -c log_statement=all -c log_destination=stderr -c log_directory=/var/log/postgresql -c log_filename=postgresql.log
    volumes:
      - flashlink_log_in_pg_v:/var/lib/postgresql/data
      - ./src/modules/database/domain/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=flashlink_db
      - POSTGRES_USER=flashlink_db_user
      - POSTGRES_PASSWORD=ptm_pg_2024
      - POSTGRES_PORT=5432
    networks:
      - flashlink_network
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'flashlink_db_user', '-d', 'flashlink_db', '-t', '1' ]
      interval: 2s
      timeout: 100s
      retries: 10

  flashlink-redis:
    image: redis:6.2.16
    container_name: flashlink_redis_c
    # 1. Start with password
    # 2. Enable disk persistence (appendonly)
    # 3. INTERNAL Logic: Tell Redis to evict old keys if it hits 100MB (leaving 28MB buffer for overhead)
    command: redis-server --requirepass "flashlink_redis_pass" --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - "6444:6379" # Optional: Open for local debugging (e.g. Redis Insight)
    volumes:
      - flashlink_redis_data:/data
    # ðŸ›‘ EXTERNAL Hard Limit: Docker kills container if it exceeds 128MB
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - flashlink_network
    healthcheck:
      # We must pass the password (-a) to ping, otherwise it fails!
      test: ["CMD", "redis-cli", "-a", "flashlink_redis_pass", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  flashlink-server:
    image: flashlink_server_i
    container_name: flashlink_server_c
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:${PORT}"
    depends_on:
      flashlink-postgres:   
        condition: service_healthy
      flashlink-redis:
        condition: service_healthy
    networks:
      - flashlink_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:$PORT"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s
    restart: unless-stopped


volumes:
  flashlink_log_in_pg_v:
  flashlink_redis_data:

networks:
  flashlink_network:
    driver: bridge
    name: flashlink_network_bridge